cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'chruby'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'adobe-illustrator-cc'
cask 'adobe-photoshop-cc'
cask 'alfred'
cask 'atom'
cask 'cinch'
cask 'cloud'
cask 'dashlane'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
csak 'google-drive'
cask 'handbrake'
cask 'iterm2'
cask 'slack'
cask 'skype'
cask 'steam'
cask 'tower'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
